import { ApiKeyType } from '@prisma/client';
import objectBuilder from './object-builder';

export const mockApiKey = objectBuilder({
  name: 'Sample API Key 1',
  description: 'This is a sample API key for testing purposes',
  status: 'ACTIVE',
  value: process.env.SEED_API_KEY ?? 'xxxxx',
  scopes: JSON.stringify([
    'read:api-keys',
    'write:api-keys',
    'read:licenses',
    'write:licenses',
    'cancel:licenses',
    'read:products',
    'write:products',
    'read:pricing-tables',
    'write:pricing-tables',
    'read:plans',
    'write:plans',
    'read:capabilities',
    'write:capabilities',
    'read:features',
    'write:features',
    'read:paddle',
    'write:paddle',
    'read:organisations',
    'write:organisations',
    'read:usage',
    'write:usage',
  ]),
  organisation: 'xxxxx',
  isTest: false,
  type: ApiKeyType.RESTRICTED,
  expiresAt: null as null | Date,
  lastUsedAt: null as null | Date,
});
