name: Clone Bitbucket Repo and test

on:
  push:
    branches: ["test/ci-cd"]

jobs:
  clone-bitbucket:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout this repository
          uses: actions/checkout@v3
          
        - name: Set up SSH agent
          uses: webfactory/ssh-agent@v0.7.0
          with:
            ssh-private-key: ${{ secrets.BITBUCKET_SSH_KEY }}
            
        - name: Add Bitbucket to known_hosts
          run: |
            mkdir -p ~/.ssh
            ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts
            
        - name: Clone Bitbucket repository
          run: |
            git clone ${{ vars.SALABLE_API_REPO_URL }}
            if [ ! -d "salable-api" ]; then
                echo "Error: Directory 'salable-api' does not exist."
                exit 1
            fi
            
        - name: Build and deploy
          env: 
            REGION: ${{ vars.REGION }}
            ENVIRONMENT: ${{ vars.ENVIRONMENT }}
            ACCOUNT: ${{ secrets.ACCOUNT }}
            SEED_API_KEY: ${{ secrets.SEED_API_KEY }}
            SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
            SEGMENT_WRITE_KEY: ${{ secrets.SEGMENT_WRITE_KEY }}
            SEGMENT_SOURCE_ID: ${{ secrets.SEGMENT_SOURCE_ID }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            SALABLE_STRIPE_SECRET_KEY: ${{ secrets.SALABLE_STRIPE_SECRET_KEY }}
            SALABLE_STRIPE_TEST_SECRET_KEY: ${{ secrets.SALABLE_STRIPE_TEST_SECRET_KEY }}
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            LAUNCHDARKLY_KEY: ${{ secrets.LAUNCHDARKLY_KEY }}
            KMS_ENCRYPTION_KEY_ARN: ${{ secrets.KMS_ENCRYPTION_KEY_ARN }}

          run: |
            cd salable-api
            npm ci
            npx prisma generate
            npx prisma db push --force-reset
            npx sst build --stage node-sdk --region ${{ vars.REGION }}
            npx sst deploy -stage node-sdk --region ${{ vars.REGION }}

            
