name: Jest tests

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

jobs:
  tests:
    name: Run Jest tests
    timeout-minutes: 15
    environment: Production
    runs-on: ${{ matrix.os }}
    env:
      SALABLE_BASE_URL: ${{ secrets.SALABLE_BASE_URL }}
      SALABLE_API_KEY: ${{ secrets.SALABLE_API_KEY }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch main branch
        run: git fetch --no-tags --depth=1000 origin main

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x.x

      - name: Install dependencies
        run: npm install

      - name: Jest Tests Overall
        run: npm run test

      - name: Jest Tests Code Coverage (branch)
        run: npm run test:coverage

      - name: Jest Tests Code Coverage (global)
        run: npm run test:globalCoverage
